
package terry_chatbot_;

import java.util.ArrayList;

import java.util.*;



public class ClubLoader {
	 
	String[] terry_organization = {
			    "Alpha Kappa Psi",
			    "AI Society at Terry",
			    "American Marketing Association",
			    "Apollo Society",
			    "Association of Latino Professionals for America",
			    "Atlas Business Society",
			    "Beta Alpha Psi",
			    "Black Business Student Association",
			    "The Corsair Society (Honors/Terry) - Consulting",
			    "The Corsair Society (Honors/Terry) - Investment Banking",
			    "The Corsair Society (Honors/Terry) - Technology",
			    "Delta Sigma Pi",
			    "Economics Society",
			    "Finance Society",
			    "Gamma Iota Sigma",
			    "Insurance Society",
			    "International Business Society",
			    "Management Society",
			    "Minorities in Technology",
			    "Multicultural Business Student Association",
			    "National Association of Black Accountants",
			    "Pi Sigma Epsilon",
			    "Real Estate Society",
			    "Sales and Trading Society",
			    "Scholars of Finance",
			    "Society for Cyber Security (SCS)",
			    "Society for Human Resource Management",
			    "Society for Management Information Systems",
			    "Society of Business Intelligence",
			    "Society of Entrepreneurs",
			    "Student Managed Investment Fund (SMIF)",
			    "Sustainable Business Society",
			    "TAMID",
			    "Terry Ambassadors",
			    "Terry FinTech Society",
			    "Terry EY Fellows, Funded by EY",
			    "Terry Student Consulting",
			    "Terry Women’s Initiative",
			    "Terry Student Researchers",
			    "UGA Mind Blowers",
			    "Women in Business",
			    "Women in Consulting",
			    "Women in Economics",
			    "Women in Finance",
			    "Women in Technology"
			
			};
	 
	 String[] meeting_time = {
			    "Tuesdays at 7pm",
			    "Wednesdays at 6:30",
			    "Tuesdays at 7pm",
			    "Tuesdays from 5:30pm-6:45pm",
			    "Wednesdays at 5pm but changes regularly depending on the event",
			    "Wednesdays from 6:30-8:00pm",
			    "Thursdays 5:30-7 + socials + service events",
			    "Varies, once a month",
			    "Varies based on cohort",
			    "Varies based on cohort",
			    "Varies based on cohort",
			    "Tuesdays at 7pm",
			    "Varies weekly",
			    "Varies",
			    "",
			    "Varies",
			    "Wednesdays at 5:30 pm",
			    "",
			    "Varies",
			    "Wednesdays at 5:30 pm",
			    "Varies weekly",
			    "",
			    "",
			    "Varies weekly",
			    "",
			    "Wednesdays at 6:30 pm to 7:30 pm",
			    "Benson Hall",
			    "Tuesdays and Thursdays 7-8 pm",
			    "Wednesdays at 6:30 pm",
			    "Tuesdays at 6pm",
			    "Wednesdays at 4:30 pm",
			    "Tuesday at 5:30 pm",
			    "Tuesday at 6 pm",
			    "Varies",
			    "Mondays at 6:30 pm",
			    "Varies",
			    "Wednesdays at 5:30 pm",
			    "Varies",
			    "based on project team availability",
			    "Varies (Zoom/in person)",
			    "bimonthly varies",
			    "Tuesday at 5:30 pm to 6:30",
			    "Varies",
			    "Find on Instagram",
			    "Wednesdays 6:30-7:30",
			    "",
			    "",
			    ""
			};

	 String[] associated_career_path = {
			    "Any",
			    "Technology",
			    "Marketing",
			    "Finance and Accounting",
			    "Any",
			    "Business",
			    "Accounting",
			    "Business ",
			    "Consulting",
			    "Investment Banking",
			    "Technology",
			    "Business",
			    "Economics",
			    "Finance",
			    "Risk Management and Insurance ",
			    "Risk Management and Insurance ",
			    "International Business",
			    "Managment/All Business",
			    "MIS/Computer Science ",
			    "Business ",
			    "Accounting",
			    "Business ",
			    "",
			    "Sales and Trading",
			    "",
			    "Information Systems/Business Tech",
			    "HR",
			    "Information Systems/Business Tech",
			    "Business Technology",
			    "Entreprenuer",
			    "Investment Banking/Finance",
			    "Business ",
			    "None",
			    "Business",
			    "FinTech",
			    "Business",
			    "Consulting",
			    "Any",
			    "Any",
			    "Philanthropy",
			    "Business ",
			    "Business",
			    "Economics",
			    "Finance",
			    "MIS/Econ",
			    "",
			    "",
			    ""
			};

	 String[] process_to_be_member = {
			    "info session, interview",
			    "None",
			    "Apply on a google form, attend 1 info session",
			    "Application and interview",
			    "None",
			    "Apply on a google form, interview round",
			    "Apply on through a google form once you are in Intermediate Accounting I, once get in pay $75",
			    "None",
			    "1st round resume drop/essay questions, 2nd round behavioral and case interview",
			    "1st round resume drop/essay questions, phone screen, and second round behavioral and technical interview",
			    "1st round resume drop/essay questions, 2nd round behavioral and technical interview",
			    "complete recruitment requirements: attend 1 info session and 2 recruitment events, go through a group and individual interview, receive a bid, go through pledgeship",
			    "Register on their website ",
			    "Apply on google form",
			    "Application",
			    "Complete the application and pay the dues ",
			    "Apply on google form",
			    "Join slack messaging group and pay dues",
			    "None",
			    "Apply on google form",
			    "interest form",
			    "Apply on google form",
			    "",
			    "application on instagram",
			    "",
			    "Apply on google form",
			    "Email to join",
			    "Join GroupMe and pay $30 yearly dues",
			    "Join GroupMe",
			    "Interest form",
			    "Application, interview",
			    "None",
			    "application on instagram",
			    "Video Application, Group Interview and Individual Interview",
			    "Fill out interest form",
			    "Application and interview ",
			    "Application and interview",
			    "None",
			    "Email with short applicationa and essay",
			    "None",
			    "None",
			    "None",
			    "Fill out google forms and go to 4 meetings a semester ",
			    "None",
			    "Can go to the meetings regardless of membership, but if want to be a member pay $10",
			    "",
			    "",
			    ""
			};
	 
	 String[] requirements_major = {
			    "No",
			    "None",
			    "",
			    "Business major",
			    "None",
			    "",
			    "Accounting passed or in Intermediate Accounting I with a 3.25GPA or higher",
			    "Business major",
			    "Second-year student",
			    "Second-year student",
			    "Second-year student",
			    "must be a business major, have 12 credit hours, 3.0 GPA, 3 semesters remaining",
			    "attend 2 events a semester",
			    "attend 4 events a semester",
			    "must be Risk Management and Insurance majors",
			    "Risk management and actuarial science certificate students ",
			    "None",
			    "None",
			    "None",
			    "None",
			    "$10 dues",
			    "None",
			    "",
			    "",
			    "",
			    "None",
			    "None",
			    "None",
			    "None",
			    "None",
			    "Finance Major",
			    "None",
			    "None",
			    "Must be sophomore or junior in terry",
			    "$30 dues",
			    "Must be a sophomore or junior in terry",
			    "None",
			    "None",
			    "None",
			    "None",
			    "None",
			    "None",
			    "None",
			    "None",
			    "None",
			    "",
			    "",
			    ""
			};

	 String[] misters_credit = {
			    "No",
			    "sometimes",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "",
			    "",
			    "",
			    "sometimes",
			    "No",
			    "Yes",
			    "Sometimes",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "Sometimes",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "No",
			    "Yes",
			    "No",
			    "No",
			    "Yes",
			    "",
			    "",
			    ""
			};

	 String[] contact_info = {
			    "president.akpsi.ae@gmail.com",
			    "kc17600@uga.edu",
			    "amaatuga@gmail.com",
			    "apollo.leadership.team@gmail.com",
			    "Dz14168@uga.edu",
			    "atlasuga@gmail.com",
			    "ugabappresident@gmail.com",
			    "ugabbsa@gmail.com",
			    "ugacorsairconsulting@gmail.com",
			    "corsairleadership@gmail.com",
			    "corsairleadership@gmail.com",
			    "ugadsp.recruitment@gmail.com",
			    "ugaeconsoc@gmail.com",
			    "ugafinancesociety@gmail.com",
			    "jrd66014@uga.edu",
			    "jenatk@uga.edu",
			    "internationalbizuga@gmail.com",
			    "theugamgmtsociety@gmail.com",
			    "mituga1785@gmail.com",
			    "rn24079@uga.edu",
			    "dac84138@uga.edu",
			    "psegammahr@gmail.com",
			    "",
			    "lhf95368@uga.edu",
			    "",
			    "ugascs@gmail.com",
			    "shrm.uga@gmail.com",
			    "ncp20496@uga.edu",
			    "harshika.mehta@uga.edu",
			    "soe@uga.edu",
			    "smif.uga@gmail.com",
			    "sustainablebusinessuga@gmail.com",
			    "mlh51701@uga.edu",
			    "sallgood@uga.edu",
			    "terryfintechsociety@gmail.com",
			    "sharnice.brown@uga.edu",
			    "tsc.interviews@gmail.com",
			    "terrywi@uga.edu",
			    "TerryStudentResearchers@gmail.com",
			    "mindblowers.terry@gmail.com",
			    "ugawib@gmail.com",
			    "ugawic@gmail.com",
			    "wieuga@gmail.com",
			    "ugawif@gmail.com",
			    "WomenInTechUGA@gmail.com",
			    "",
			    "",
			    ""
			};
	 

	 public ArrayList<Club> loadAllClubs() {
	        ArrayList<Club> clubs = new ArrayList<>();

	        for (int i = 0; i < terry_organization.length; i++) {
	            if (terry_organization[i].isEmpty() || contact_info[i].isEmpty()) continue;

	            String name = terry_organization[i];
	            String meeting = i < meeting_time.length ? meeting_time[i] : "Varies";
	            String career = i < associated_career_path.length ? associated_career_path[i] : "Any";
	            String membership = i < process_to_be_member.length ? process_to_be_member[i] : "Not specified";
	            String majorReq = i < requirements_major.length ? requirements_major[i] : "None";
	            String mistersRaw = i < misters_credit.length ? misters_credit[i] : "no";
	            String contact = i < contact_info.length ? contact_info[i] : "Not available";

	            boolean misters = mistersRaw.equalsIgnoreCase("yes") || mistersRaw.equalsIgnoreCase("sometimes");

	            Club club = new Club(name, meeting, career, membership, majorReq, misters, contact);
	            clubs.add(club);
	        }

	        return clubs;
	    }
	}